language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "michelesalvatori"
    token: "62063c17bc6d8076dd6cfba71251970e0ca142ae"
     
script:
  - mvn clean verify -e org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=MicheleSalvatori_bookkeeper